shopee_brands = {
    4655: 'tets'
}

base_category = "Makanan & Minuman"

sub_category_urls = ['/bahan-kue/bahan-puding-agar-agar',
                     '/bahan-kue/baking-powder',
                     '/bahan-kue/baking-soda',
                     '/bahan-kue/coklat-bubuk',
                     '/bahan-kue/coklat-masak',
                     '/bahan-kue/perisa-makanan',
                     '/bahan-kue/pewarna-makanan',
                     '/bahan-kue/ragi',
                     '/bahan-kue/topping-penghias-kue',
                     '/beras/beras-hitam',
                     '/beras/beras-ketan',
                     '/beras/beras-merah',
                     '/beras/beras-putih',
                     '/bumbu-bahan-masakan/aneka-sambal',
                     '/bumbu-bahan-masakan/bawang',
                     '/bumbu-bahan-masakan/bumbu-masak-instan',
                     '/bumbu-bahan-masakan/cuka',
                     '/bumbu-bahan-masakan/garam-merica',
                     '/bumbu-bahan-masakan/gula',
                     '/bumbu-bahan-masakan/kaldu-penyedap-rasa',
                     '/bumbu-bahan-masakan/kecap',
                     '/bumbu-bahan-masakan/mayonnaise',
                     '/bumbu-bahan-masakan/minyak',
                     '/bumbu-bahan-masakan/rempah',
                     '/bumbu-bahan-masakan/santan',
                     '/bumbu-bahan-masakan/saus-dressing',
                     '/bumbu-bahan-masakan/terasi',
                     '/kopi/biji-kopi',
                     '/kopi/kopi-bubuk',
                     '/kopi/kopi-kemasan',
                     '/kopi/krimer',
                     '/kue/kue-basah',
                     '/kue/kue-kering',
                     '/kue/kue-ulang-tahun',
                     '/makanan-beku/baso-daging-olahan-lainnya',
                     '/makanan-beku/buah-beku',
                     '/makanan-beku/camilan-beku',
                     '/makanan-beku/daging-sosis',
                     '/makanan-beku/dessert',
                     '/makanan-beku/kentang-beku',
                     '/makanan-beku/nugget',
                     '/makanan-beku/pastry-olahan-tepung',
                     '/makanan-beku/sayuran-beku',
                     '/makanan-beku/sosis',
                     '/makanan-jadi/buah-olahan',
                     '/makanan-jadi/lauk-pauk',
                     '/makanan-jadi/makanan-asin',
                     '/makanan-jadi/makanan-manis',
                     '/makanan-jadi/nasi-tumpeng',
                     '/makanan-jadi/sayur-olahan',
                     '/makanan-kaleng/buah-kaleng',
                     '/makanan-kaleng/daging-kaleng',
                     '/makanan-kaleng/ikan-kaleng',
                     '/makanan-kaleng/makanan-instan-kaleng',
                     '/makanan-kering/abon',
                     '/makanan-kering/bawang-goreng',
                     '/makanan-kering/biji-bijian',
                     '/makanan-kering/daging-kering-asin',
                     '/makanan-kering/kerupuk',
                     '/makanan-ringan/biskuit-wafer',
                     '/makanan-ringan/camilan-instant',
                     '/makanan-ringan/cokelat',
                     '/makanan-ringan/kacang',
                     '/makanan-ringan/keripik',
                     '/makanan-ringan/permen',
                     '/makanan-ringan/puding-jelly',
                     '/makanan-sarapan/granola',
                     '/makanan-sarapan/meses',
                     '/makanan-sarapan/muesli',
                     '/makanan-sarapan/oat',
                     '/makanan-sarapan/quinoa',
                     '/makanan-sarapan/roti',
                     '/makanan-sarapan/selai',
                     '/makanan-sarapan/sereal',
                     '/mie-pasta/aneka-pasta',
                     '/mie-pasta/bihun-soun',
                     '/mie-pasta/kwetiau',
                     '/mie-pasta/mie-impor',
                     '/mie-pasta/mie-instan',
                     '/mie-pasta/mie-telur',
                     '/minuman/air-mineral',
                     '/minuman/apple-cider-vinegar',
                     '/minuman/bubuk-minuman-lainnya',
                     '/minuman/energy-drink',
                     '/minuman/jus',
                     '/minuman/madu',
                     '/minuman/minuman-cokelat',
                     '/minuman/minuman-kemasan-lainnya',
                     '/minuman/minuman-tradisional',
                     '/minuman/sirup',
                     '/minuman/soft-drink',
                     '/paket-parcel-makanan/paket-sembako',
                     '/paket-parcel-makanan/parcel-buah',
                     '/paket-parcel-makanan/parcel-coklat',
                     '/paket-parcel-makanan/parcel-kue-kering',
                     '/paket-parcel-makanan/parcel-makanan',
                     '/produk-susu/keju',
                     '/produk-susu/krim',
                     '/produk-susu/mentega-butter',
                     '/produk-susu/susu-bubuk',
                     '/produk-susu/susu-kedelai-kacang-kacangan',
                     '/produk-susu/susu-kental-manis',
                     '/produk-susu/susu-lansia',
                     '/produk-susu/susu-segar-pasteurisasi',
                     '/produk-susu/susu-uht',
                     '/produk-susu/yogurt',
                     '/protein-telur/daging-ayam',
                     '/protein-telur/daging-kambing',
                     '/protein-telur/daging-lainnya',
                     '/protein-telur/daging-sapi',
                     '/protein-telur/ikan',
                     '/protein-telur/seafood',
                     '/protein-telur/tahu-tempe',
                     '/protein-telur/telur',
                     '/sayur-buah/buah-buahan',
                     '/sayur-buah/jamur',
                     '/sayur-buah/sayuran',
                     '/teh/daun-teh',
                     '/teh/teh-bubuk',
                     '/teh/teh-kemasan',
                     '/tepung/tepung-beras-ketan',
                     '/tepung/tepung-bumbu-tepung-siap-pakai',
                     '/tepung/tepung-jagung',
                     '/tepung/tepung-kentang',
                     '/tepung/tepung-roti-panir',
                     '/tepung/tepung-sagu',
                     '/tepung/tepung-tapioka',
                     '/tepung/tepung-terigu-gandum']

main_categories = [
    "Bahan Kue",
    "Beras",
    "Bumbu & Bahan Masakan",
    "Kopi",
    "Kue",
    "Makanan Beku",
    "Makanan Jadi",
    "Makanan Kaleng",
    "Makanan Kering",
    "Makanan Ringan",
    "Makanan Sarapan",
    "Mie & Pasta",
    "Minuman",
    "Paket & Parcel Makanan",
    "Produk Susu",
    "Protein & Telur",
    "Sayur & Buah",
    "Teh",
    "Tepung",
]

sub_categories = [
    "Bahan Puding & Agar - Agar",
    "Baking Powder",
    "Baking Soda",
    "Coklat Bubuk",
    "Coklat Masak",
    "Perisa Makanan",
    "Pewarna Makanan",
    "Ragi",
    "Topping & Penghias Kue",
    "Beras Hitam",
    "Beras Ketan",
    "Beras Merah",
    "Beras Putih",
    "Aneka Sambal",
    "Bawang",
    "Bumbu Masak Instan",
    "Cuka",
    "Garam & Merica",
    "Gula",
    "Kaldu & Penyedap Rasa",
    "Kecap",
    "Mayonnaise",
    "Minyak",
    "Rempah",
    "Santan",
    "Saus & Dressing",
    "Terasi",
    "Biji Kopi",
    "Kopi Bubuk",
    "Kopi Kemasan",
    "Krimer",
    "Kue Basah",
    "Kue Kering",
    "Kue Ulang Tahun",
    "Baso & Daging Olahan Lainnya",
    "Buah Beku",
    "Camilan Beku",
    "Daging Sosis",
    "Dessert",
    "Kentang Beku",
    "Nugget",
    "Pastry & Olahan Tepung",
    "Sayuran Beku",
    "Sosis",
    "Buah Olahan",
    "Lauk Pauk",
    "Makanan Asin",
    "Makanan Manis",
    "Nasi Tumpeng",
    "Sayur Olahan",
    "Buah Kaleng",
    "Daging Kaleng",
    "Ikan Kaleng",
    "Makanan Instan Kaleng",
    "Abon",
    "Bawang Goreng",
    "Biji-bijian",
    "Daging Kering & Asin",
    "Kerupuk",
    "Biskuit & Wafer",
    "Camilan Instant",
    "Cokelat",
    "Kacang",
    "Keripik",
    "Permen",
    "Puding & Jelly",
    "Granola",
    "Meses",
    "Muesli",
    "Oat",
    "Quinoa",
    "Roti",
    "Selai",
    "Sereal",
    "Aneka Pasta",
    "Bihun & Soun",
    "Kwetiau",
    "Mie Impor",
    "Mie Instan",
    "Mie Telur",
    "Air Mineral",
    "Apple Cider Vinegar",
    "Bubuk Minuman Lainnya",
    "Energy Drink",
    "Jus",
    "Madu",
    "Minuman Cokelat",
    "Minuman Kemasan Lainnya",
    "Minuman Tradisional",
    "Sirup",
    "Soft Drink",
    "Paket Sembako",
    "Parcel Buah",
    "Parcel Coklat",
    "Parcel Kue Kering",
    "Parcel Makanan",
    "Keju",
    "Krim",
    "Mentega & Butter",
    "Susu Bubuk",
    "Susu Kedelai & Kacang-kacangan",
    "Susu Kental Manis",
    "Susu Lansia",
    "Susu segar & Pasteurisasi",
    "Susu UHT",
    "Yogurt",
    "Daging Ayam",
    "Daging Kambing",
    "Daging Lainnya",
    "Daging Sapi",
    "Ikan",
    "Seafood",
    "Tahu & Tempe",
    "Telur",
    "Buah-buahan",
    "Jamur",
    "Sayuran",
    "Daun Teh",
    "Teh Bubuk",
    "Teh Kemasan",
    "Tepung Beras & Ketan",
    "Tepung Bumbu & Tepung Siap Pakai",
    "Tepung Jagung",
    "Tepung Kentang",
    "Tepung Roti - Panir",
    "Tepung Sagu",
    "Tepung Tapioka",
    "Tepung Terigu & Gandum",
]
